### ISSUE TITLE
RFC: Sound effects ideas

### ISSUE THREAD

**Issue by Samathingamajig** [Samathingamajig/ap-score-hider#2]
WIP

Some thoughts I've had on adding sound effects.

## Positive
- Charlie "WOOO YEAH BABY!! THAT'S WHAT I'VE BEEN WAITING FOR, THAT'S WHAT IT'S ALL ABOUT" https://youtu.be/sAXZbfLzJUg
- Noice https://youtu.be/a8c5wmeOL9o
- Super Mario Bros flag pole https://youtu.be/3BsBXp6VkvU
- Mario Kart Wii trophy https://youtu.be/u_V7EO44Qxs?t=18
- 

## Negative
- Charlie "It was a misinput" https://youtu.be/tjOAqCIIaAw
- Sad trombone
-

Should it be a random sound or customizable? Should specific sounds be for each possible score (5 different total sounds)?

Also, would a delay be good, such as with the Jaws sound effect and reveal the score afterwards (this sound wouldn't be dependent on scores)

**Comment by benf2004** [comment]
Here is what I'm envisioning:
1. When you install the extension, a simple setup UI page opens (using the `chrome.runtime.onInstalled` listener). 
2. You can then select a sound for each number 1-5 using a simple dropdown. Also allow a custom MP3 sound (maybe YouTube but that seems to be more complicated).
The sounds you choose would be saved in an object (in `chrome.storage.local`) like this: 
```
{
  1: "mysoundchoice.mp3",
  2: "sound2.mp3",
...
}
```
Then injecting it into the AP page would be pretty straightforward.
4. As a bonus, there is a big countdown until July 5th.

**Comment by benf2004** [comment]
Also, FYI it takes a few days for Chrome to approve an extension so you'll want to ship it within the next day or two if you're going to add anything.

**Comment by Samathingamajig** [comment]
> Here is what I'm envisioning:
> 
> 1. When you install the extension, a simple setup UI page opens (using the `chrome.runtime.onInstalled` listener).
> 2. You can then select a sound for each number 1-5 using a simple dropdown. Also allow a custom MP3 sound (maybe YouTube but that seems to be more complicated).
>    The sounds you choose would be saved in an object (in `chrome.storage.local`) like this:
> 
> ```
> {
>   1: "mysoundchoice.mp3",
>   2: "sound2.mp3",
> ...
> }
> ```
> 
> Then injecting it into the AP page would be pretty straightforward. 4. As a bonus, there is a big countdown until July 5th.

@benf2004 would you be available to write that today/tomorrow, just the custom mp3 part (I don't want to have this rejected for including audio that's copyrighted; & not the countdown, for this change, sounds like a good idea for a separate PR), with a link to this issue? It should also be accessible when clicking on the extension icon (as a separate page, not the popup). Remember to pull from my `main` branch.

I'm working through getting it approved for the web store, won't submit anything until we have sounds or decide not to do it. Turns out the [icons shouldn't be at the max size they can be](https://developer.chrome.com/docs/webstore/images/#icons), but I can fix that.

If you're not available, let me know and I'll try to figure it out.

**Comment by benf2004** [comment]
Yeah, I can whip something up.
